### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by RubyTemple** [AetherNetwork/WorldTpUI-Nukkit#2]
I want to create a huge universal network that will be very successful and your programming skills would help me a lot can you help me

**Comment by AvgZing** [comment]
I believe the error that "wontfix" in this issue is *you*. Invalid.

**Comment by RubyTemple** [comment]
Is for the creator I stay make a international network can you help me? @ItaSkyGames on Telegram or Twitter

**Comment by ZeroDevOfficial** [comment]
@Emis02 sorry but I must agree this is invalid, as much as I love the offer, I'm sorry to say but I quit playing Minecraft and quit programming for it. Certain issues have come up in my life and it prevents me from doing so, I do hope you can understand

**Comment by RubyTemple** [comment]
No problem
